version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .          # installs your package so autodoc works

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
  - epub
